[tool.poetry]
name = "vss365-today-api"
version = "0.1.0"
description = ""
authors = ["Caleb Ely <le717@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
webargs = "^5.5.2"
flask = "^1.1.1"
python-dotenv = "^0.10.3"
gunicorn = "19.9"
pyjwt = "^1.7.1"
records = "^0.5.3"
pymysql = "^0.9.3"
Flask-Cors = "^3.0.8"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "^0.740"
autopep8 = "^1.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
